# Generated by Django 4.0.4 on 2022-07-25 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='remainingDays',
        ),
        migrations.AddField(
            model_name='challengemember',
            name='remaining_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='challengemember',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengemember',
            name='streak_updated_at',
            field=models.DateField(default=datetime.date(2022, 7, 26)),
        ),
    ]
